{{- if .Values.dummyConfigInCI }}
# Need this dummy config for pipeline builds only; it is ignored in full CCD deployments.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    system: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    type: configuration
{{- end}}
