---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hmcts.ccdupi.releaseName" . }}
  labels:
    {{- ( include "ccdupi.labels" . ) | indent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "100"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "hmcts.ccdupi.releaseName" . }}
      labels:
          {{- ( include "ccdupi.labels" . ) | indent 4 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "hmcts.ccdupi.releaseName" . }}
          image: {{ .Values.image }} 
          imagePullPolicy: IfNotPresent
          env:
          - name: CCD_USER_PROFILE_URL
            value: {{ .Values.userProfileUrl }}
          - name: AUTH_PROVIDER_BASE_URL
            value: {{ .Values.s2sUrl }}
          - name: MICROSERVICE
            value: {{ .Values.microservice }}
          - name: CCD_USERS
            value: {{ join "," .Values.users | quote }}
          - name: CCD_JURISDICTIONS
            value: {{ join "," .Values.jurisdictions | quote }}
          - name: WAIT_HOSTS
            value: {{ .Values.waitHosts | quote }}
          - name: WAIT_HOSTS_TIMEOUT
            value: {{ .Values.waitHostsTimeout | quote }}
          - name: CCD_USER_PROFILE_DB_HOST
            value: {{ .Values.userProfileDatabaseHost | quote }}
          - name: CCD_USER_PROFILE_DB_PORT
            value: {{ .Values.userProfileDatabasePort | quote }}
          - name: CCD_USER_PROFILE_DB_USERNAME
            value: {{ .Values.userProfileDatabaseUser | quote }}
          - name: CCD_USER_PROFILE_DB_PASSWORD
            value: {{ .Values.userProfileDatabasePassword | quote }}
          - name: CCD_USER_PROFILE_DB_DATABASE
            value: {{ .Values.userProfileDatabaseName | quote }}
          - name: VERBOSE
            value: {{ .Values.verbose | quote }}
          resources:
            requests:
              memory: {{ .Values.memoryRequests }}
              cpu: {{ .Values.cpuRequests }}
            limits:
              memory: {{ .Values.memoryLimits }}
              cpu: {{ .Values.cpuLimits }}