dummyConfigInCI: true   #This Flag enables dummy-config for pipleine build only
users:
  - adasari123.hmcts.claimant+1@gmail.com|CMC|MoneyClaimCase|open
verbose: true
 
global:
  subscriptionId: "1c4f0704-a29e-403d-b719-b90c34ef14c9"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"



   