image: 'hmctspublic.azurecr.io/ccd/user-profile-importer:latest'
memoryRequests: '512Mi'
cpuRequests: '250m'
memoryLimits: '2048Mi'
cpuLimits: '1500m'
userProfileUrl: http://ccd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
s2sUrl: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
users: 
waitHosts: ""
waitHostsTimeout: 300
microservice: ccd_definition
verbose: "false"

global:
  environment: aat

